### ISSUE TITLE
add a cherry sign block loot table and recipe

### ISSUE THREAD

**Issue by spunchbop121** [gigaherz/signbutton#3]

**Comment by spunchbop121** [comment]
[Fixes.zip](https://github.com/gigaherz/signbutton/files/12454100/Fixes.zip)

**Comment by gigaherz** [comment]
Oh did I forget them? oops!
I'll fix as soon as I can. Thanks!

**Comment by gigaherz** [comment]
Fixed in 2.5.4. Thanks!
